import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const emailToRespondTo = body.email || body.emailAddress || undefined;
    const company = body.company || body.companyName || "Website Visitor";
    
    console.log("Processing contact form submission...");

    // Create a nodemailer transporter
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || "mail.perlogy.africa",
      port: Number(process.env.SMTP_PORT || 465),
      secure: Number(process.env.SMTP_PORT) === 465 || !process.env.SMTP_PORT, // true for 465, false for 587
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });

    // Format all submitted fields dynamically
    const fieldsHtml = Object.entries(body)
      .map(([key, value]) => `<tr><td style="padding: 8px; border-bottom: 1px solid #ddd;"><strong>${key.charAt(0).toUpperCase() + key.slice(1)}:</strong></td><td style="padding: 8px; border-bottom: 1px solid #ddd;">${value}</td></tr>`)
      .join("");

    const htmlContent = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #0F1E45;">New Website Contact Submission</h2>
        <p>A new lead has submitted a form from <strong>perlogy.co.ke</strong>.</p>
        <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
          ${fieldsHtml}
        </table>
        <p style="color: #666; font-size: 12px; margin-top: 30px;">This email was automatically generated by the Perlogy website backend.</p>
      </div>
    `;

    // Send the email
    await transporter.sendMail({
      from: `"Perlogy Website" <${process.env.SMTP_USER}>`, 
      to: "info@perlogy.africa",
      replyTo: emailToRespondTo,
      subject: `New Lead: Website Contact Form from ${company}`,
      html: htmlContent,
    });

    return NextResponse.json(
      { success: true, message: "Form submitted successfully" },
      { status: 200 }
    );
  } catch (error) {
    console.error("Error processing contact form:", error);
    return NextResponse.json(
      { success: false, error: "Internal Server Error" },
      { status: 500 }
    );
  }
}
