import { NextResponse } from "next/server";
import { Resend } from "resend";

export async function POST(request: Request) {
  try {
    const resend = new Resend(process.env.RESEND_API_KEY);
    
    const body = await request.json();
    const emailToRespondTo = body.email || body.emailAddress || undefined;
    const company = body.company || body.companyName || "Website Visitor";
    
    console.log("Processing contact form submission...");

    // Format all submitted fields dynamically
    const fieldsHtml = Object.entries(body)
      .map(([key, value]) => `<tr><td style="padding: 8px; border-bottom: 1px solid #ddd;"><strong>${key.charAt(0).toUpperCase() + key.slice(1)}:</strong></td><td style="padding: 8px; border-bottom: 1px solid #ddd;">${value as string}</td></tr>`)
      .join("");

    const htmlContent = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #0F1E45;">New Website Contact Submission</h2>
        <p>A new lead has submitted a form from <strong>perlogy.co.ke</strong>.</p>
        <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
          ${fieldsHtml}
        </table>
        <p style="color: #666; font-size: 12px; margin-top: 30px;">This email was automatically generated by the Perlogy website backend (Resend).</p>
      </div>
    `;

    // Send the email using Resend
    const { data, error } = await resend.emails.send({
      from: "Perlogy Website <info@perlogy.co.ke>",
      to: ["info@perlogy.africa"],
      replyTo: emailToRespondTo,
      subject: `New Lead: Website Contact Form from ${company}`,
      html: htmlContent,
    });

    if (error) {
      console.error("Resend error:", error);
      return NextResponse.json(
        { success: false, error: error.message || "Failed to send email" },
        { status: 500 }
      );
    }

    return NextResponse.json(
      { success: true, message: "Form submitted successfully", data },
      { status: 200 }
    );
  } catch (error: any) {
    console.error("Error processing contact form:", error);
    return NextResponse.json(
      { success: false, error: error?.message || "Internal Server Error" },
      { status: 500 }
    );
  }
}

